name: Shared actions
on:
  repository_dispatch:
    types:
      - red
      - blue
jobs:
  shared_action_definitions:
    name: Shared action A
    runs-on: ubuntu-latest
    steps:
      - name: Display shared action content
        run: echo "Printing in shared-ci repo using shared_actions.yml workflow."
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: anup350/${{ github.event }}
          # token: ${{ secrets.my_pat }}
      - name: Display current folder content
        run: ls -latr