name: Shared actions
on:
  repository_dispatch:
    types:
      - red
      - blue
jobs:
  shared_action_definitions:
    # if: ${{ github.event }} == "red"
    name: Shared action A
    runs-on: ubuntu-latest
    steps:
      - name: Display shared action content
        run: echo "Printing in shared-ci repo using shared_actions.yml workflow."
