name: Shared actions
on:
  repository_dispatch:
    types:
      - red
      - blue
jobs:
  shared_action_definitions:
    name: Shared action job
    runs-on: ubuntu-latest
    steps:
      - name: Display shared action content
        run: echo "Event name = ${{ github.event_name }}"
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: anup350/shared-${{ github.event_name }}
          # token: ${{ secrets.my_pat }}
      - name: Display current folder content
        run: ls -latr